
description: His name is Muhammad Ghifar Ziady He was born in Dayah Tanoh on July 11, 2000, he is the first child of Adhiyati and Ramli who lives in Beureunuen City, Mutiara Timur District, Pidie District, Aceh.

title: Resume GhifarZy
# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
#github_username: abhn
#blog_url: https://www.nagekar.com
#email: abhishek@nagekar.com
#keybase_username: abhn
#twitter_username: abhn_
#reddit_username: abhn

# absolute or relative
#profile_picture: assets/images/ifar.jpg

# Google Analytics ID
#google_analytics: 
