
description: His name is Muhammad Ghifar Ziady He was born in Dayah Tanoh on July 11, 2000, he is the first child of Adhiyati and Ramli who lives in Beureunuen City, Mutiara Timur District, Pidie District, Aceh.
alamat:  Indonesia, Banda Aceh · 085232296159 ·
email:  ifarziady123@gmail.com
title: Resume GhifarZy
# Build settings
markdown: kramdown
exclude: [vendor/ruby]


